### ISSUE TITLE
I'm getting a node.js error message while trying to run.

### ISSUE THREAD

**Issue by wisplite** [Oblivionburn/RealAI-Discord-Bot#2]
Whenever I run the deploy.bat file, I get this error:

        throw new Error(`Please install ${moduleName} package manually`);
        ^

Error: Please install sqlite3 package manually
    at ConnectionManager._loadDialectModule (Z:\RealAI-Discord-Bot-master\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:81:15)
    at new ConnectionManager (Z:\RealAI-Discord-Bot-master\node_modules\sequelize\lib\dialects\sqlite\connection-manager.js:22:21)
    at new SqliteDialect (Z:\RealAI-Discord-Bot-master\node_modules\sequelize\lib\dialects\sqlite\index.js:14:30)
    at new Sequelize (Z:\RealAI-Discord-Bot-master\node_modules\sequelize\lib\sequelize.js:324:20)
    at new Brain (Z:\RealAI-Discord-Bot-master\brain\brain.js:7:25)
    at Object.<anonymous> (Z:\RealAI-Discord-Bot-master\bot.js:32:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

What am I doing wrong? There's no documentation for this bot, so I don't know what else I'm supposed to do.

Edit: The bot magically works now? I have no clue what the problem was, but I guess it works...

**Comment by wisplite** [comment]
Update: I tried to rebuild it to see if that was the problem, but then I got this result:

z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(582): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(583): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(584): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(585): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(586): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(587): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(588): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(589): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(590): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(591): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(593): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(594): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(595): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(596): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(597): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(598): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(599): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(600): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(601): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(602): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(603): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(604): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(605): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(606): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(608): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(615): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(616): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(617): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(618): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(619): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(620): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(621): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(622): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(623): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(624): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(625): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(626): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(627): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(628): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(629): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(630): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(631): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(632): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(633): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(634): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(635): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(636): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(637): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(638): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(641): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(642): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [Z:\RealAI-Discord-Bot-master\node_modules\ref\build
\binding.vcxproj]
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(643): warning C4996: 'Nan::ForceSet': was declared deprecated [Z:\RealAI-Discord-Bot-master\node_modules\ref\build\binding.vcxproj]
  z:\realai-discord-bot-master\node_modules\nan\nan_maybe_43_inl.h(117): note: see declaration of 'Nan::ForceSet'
z:\realai-discord-bot-master\node_modules\ref\src\binding.cc(644): warning C4996: 'Nan::ForceSet': was declared deprecated [Z:\RealAI-Discord-Bot-master\node_modules\ref\build\binding.vcxproj]
  z:\realai-discord-bot-master\node_modules\nan\nan_maybe_43_inl.h(117): note: see declaration of 'Nan::ForceSet'

**Comment by Oblivionburn** [comment]
Error says "Please install sqlite3 package manually", so you'll need to
open a command prompt and navigate to where the bot.js is then run "npm
install sqlite3".
